import React from 'react';
import './index.scss'


const Week = () => {
    return (
        <div class="lines">
            <div class="calendar__day">
                <div class="calendar_day-line"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
            </div>
            <div class="calendar__day">
                <div class="calendar_day-line"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
            </div>
            <div class="calendar__day">
                <div class="calendar_day-line"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
            </div>
            <div class="calendar__day">
                <div class="calendar_day-line"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
            </div>
            <div class="calendar__day">
                <div class="calendar_day-line"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
            </div>
            <div class="calendar__day">
                <div class="calendar_day-line"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
            </div>
            <div class="calendar__day">
                <div class="calendar_day-line"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
                <div class="calendar_day-active"></div>
            </div>
        </div>
    )
};


export default Week;